```yaml
name: API Rate Limit Check

on:
  push:
    branches:
      - main

jobs:
  check-api-rate-limit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test API Rate Limit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const rateLimit = await github.rest.rateLimit.get();
            if (rateLimit.data.remaining < 100) {
              console.log(`Rate limit low (${rateLimit.data.remaining} remaining). Delaying 5 minutes.`);
              await new Promise(resolve => setTimeout(resolve, 300000));
            }

      - name: Post Rate Limit Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.issue.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'API rate limit check completed at 05:36 PM EDT.'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
