```yaml
name: API Timeout Check

on:
  push:
    branches:
      - main

jobs:
  check-api-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test API Response
        run: |
          time=$(curl -m 5 -o /dev/null -s -w "%{time_total}\n" https://vial.github.io/api/mcp/health)
          if (( $(echo "$time > 5.0" | bc -l) )); then
            echo "API response too slow: $time seconds"
          fi

      - name: Post Timeout Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'API timeout check completed at 06:06 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
