```yaml
name: Database Connection Check

on:
  push:
    branches:
      - main

jobs:
  check-db-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Database Connection
        run: |
          docker run --rm -e MONGO_URI=mongodb://localhost:27017/test mongo mongosh --eval "db.runCommand({ ping: 1 })" || echo "MongoDB connection failed."
          redis-cli -h localhost ping || echo "Redis connection failed."

      - name: Post DB Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.issue.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Database connection check completed at 05:12 PM EDT, 08/24/2025.'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
