# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SQLALCHEMY_DATABASE_URL=sqlite:///vial.db
      - REDIS_HOST=redis
      - WEBXOS_WALLET_ADDRESS=e8aa2491-f9a4-4541-ab68-fe7a32fb8f1d
      - SECRET_KEY=your-secret-key-here
      - REPUTATION_LOGGING_ENABLED=true
      - API_PORT=8000
      - VERCEL_TOKEN=your-vercel-token-here
    depends_on:
      - redis
    volumes:
      - ./server:/app/server
      - ./scripts:/app/scripts
      - ./public:/app/public
      - ./pages:/app/pages

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - app

  vercel:
    image: node:18
    command: npx vercel dev --token $VERCEL_TOKEN
    environment:
      - VERCEL_TOKEN=your-vercel-token-here
    volumes:
      - ./public:/app/public
      - ./pages:/app/pages
      - ./vercel.json:/app/vercel.json
    ports:
      - "3000:3000"
    depends_on:
      - app
