version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQL_URL=sqlite:///vial.db
      - MONGODB_URL=mongodb://mongodb:27017/vial
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    volumes:
      - ./data:/app/data
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongodb_data:
