version: '3.8'
services:
  vial-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SQLALCHEMY_DATABASE_URL=sqlite:///vial.db
      - JWT_SECRET=${JWT_SECRET}
      - DEBUG=${DEBUG}
      - VERCEL_API_TOKEN=${VERCEL_API_TOKEN}
      - VERCEL_PROJECT_ID=${VERCEL_PROJECT_ID}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  nextjs-frontend:
    build:
      context: ./public
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://vial-mcp:8000
    depends_on:
      - vial-mcp
    restart: unless-stopped
volumes:
  mongodb_data:
