version: '3.9'
services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.final
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Placeholder: OBS/SVG environment variables
      # - OBS_WEBSOCKET_URL=ws://obs:4455
    volumes:
      - ./vial_mcp.db:/app/vial_mcp.db
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
