```yaml
name: Docker Build Check

on:
  push:
    branches:
      - main

jobs:
  check-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t webxos-vial-mcp -f Dockerfile .
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}

      - name: Post Build Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.issue.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Docker build succeeded at 05:05 PM EDT.'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
