version: "3.8"
services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mcp:/app/mcp
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
