version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server/data:/app/data
      - ./public:/app/public
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  data:
