[server]
name = "mcp-alchemist"
version = "2.9.3"
endpoint = "ws://localhost:8000/alchemist/ws"
stdio_command = "python -m server.mcp_server"

[tools]
vial_status_get = { name = "vial.status.get", description = "Get status of a vial by ID", handler = "server.services.mcp_alchemist" }
vial_config_generate = { name = "vial.config.generate", description = "Generate visual config from prompt", handler = "server.services.mcp_alchemist" }
deploy_vercel = { name = "deploy.vercel", description = "Deploy to Vercel with config", handler = "server.services.mcp_alchemist" }
git_commit_push = { name = "git.commit.push", description = "Commit code to GitHub", handler = "server.services.mcp_alchemist" }
quantum_circuit_build = { name = "quantum.circuit.build", description = "Build quantum circuit from components", handler = "server.services.mcp_alchemist" }

[resources]
backup_dir = "resources/backups"
svg_dir = "resources/svg"
code_dir = "resources/code"
connections_dir = "resources/connections"

[auth]
method = "oauth2"
token_url = "/alchemist/auth/token"
scopes = ["wallet:read", "wallet:export", "git:push", "vercel:deploy", "vial:train", "ops:troubleshoot", "quantum:circuit"]
