[tools]
[tools.quantum_sync]
name = "quantum_sync"
description = "Run quantum circuit with Qiskit"
handler = "server.models.mcp_alchemist.quantum_sync"

[tools.llm_route]
name = "llm_route"
description = "Route to multiple LLMs"
handler = "server.services.llm_router.route_request"

[tools.nasa_data]
name = "nasa_data"
description = "Fetch NASA API data"
handler = "server.api.nasa.query_nasa"

[tools.servicenow_query]
name = "servicenow_query"
description = "Query ServiceNow table"
handler = "server.api.servicenow.query_servicenow"

[tools.alibaba_query]
name = "alibaba_query"
description = "Query Alibaba Cloud service"
handler = "server.api.alibaba.query_alibaba"

# Placeholder: OBS/SVG video tools
[tools.svg_video_render]
name = "svg_video_render"
description = "Render SVG to video frames"
handler = "server.video.obs_handler.render_svg"

# Placeholder: Tauri desktop admin tool
[tools.tauri_admin]
name = "tauri_admin"
description = "Manage MCP server via Tauri"
handler = "server.frontend.tauri_main.admin_command"
