[mcp]
version = "2025-03-26"
name = "WebXOS 2025 Vial MCP SDK"
description = "Data Science and Space Exploration Laboratory with LangChain"
endpoint = "https://vial.github.io/api/mcp"

[capabilities]
dropship = true
galaxycraft = true
telescope = true
alchemist = true
svg_transpiler = true
langchain_agents = true
dao_wallet = true
quantum_distribution = true
arvr_overlay = true
benchmarking = true

[auth]
method = "oauth2"
token_url = "https://vial.github.io/token"
scopes = ["read", "write", "admin", "collaboration"]

[server]
host = "0.0.0.0"
port = 8000
healthcheck = "/healthz"
session_timeout = 3600

