```yaml
name: OAuth Scope Check

on:
  push:
    branches:
      - main

jobs:
  check-oauth-scope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify OAuth Scopes
        run: |
          node -e "const fs = require('fs'); const config = JSON.parse(fs.readFileSync('mcp-client-config.json')); const requiredScopes = ['read', 'write']; if (!config.auth.scopes.every(s => requiredScopes.includes(s))) throw new Error('Invalid OAuth scopes');"

      - name: Post Scope Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'OAuth scope check completed at 06:02 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
