# pyproject.toml
[project]
name = "vial-mcp-controller"
version = "1.0.0"
description = "Vial MCP Controller with WebXOS wallet and reputation system"
authors = [{ name = "xAI", email = "support@x.ai" }]
license = { text = "MIT" }
dependencies = [
    "fastapi==0.103.2",
    "uvicorn==0.23.2",
    "sqlalchemy==2.0.21",
    "pydantic-settings==2.0.3",
    "torch==2.0.1",
    "redis==4.6.0",
    "pytest==7.4.2",
    "pytest-asyncio==0.21.1",
    "alembic==1.12.0"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"
