[project]
name = "vial-mcp-controller"
version = "2.7.0"
description = "Modular control plane for AI-driven task management with quantum and wallet integration"
authors = [
    { name = "Vial Team", email = "contact@vial.github.io" }
]
license = { file = "LICENSE" }
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.103.0",
    "uvicorn>=0.23.0",
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",
    "pymongo>=4.0.0",
    "torch>=2.0.0",
    "qiskit>=0.44.0",
    "web3>=6.0.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.0.0",
    "redis>=5.0.0",
    "pytest>=7.0.0",
    "flake8>=6.0.0",
    "langchain>=0.0.300",
    "aiofiles>=23.2.0",
    "psycopg2-binary>=2.9.0",
    "gitpython>=3.1.0",
    "octokit>=0.11.0"
]

[project.urls]
Homepage = "https://github.com/vial/vial.github.io"
Documentation = "https://vial.github.io/docs"
Repository = "https://github.com/vial/vial.github.io"
Issues = "https://github.com/vial/vial.github.io/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["server/tests"]

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
