[project]
name = "vial-mcp-controller"
version = "2.7.0"
description = "A modular control plane for AI-driven task management with GitHub and quantum computing"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "pydantic>=2.9.0",
    "httpx>=0.27.0",
    "pymongo>=4.8.0",
    "redis>=5.0.0",
    "qiskit>=1.2.0",
    "python-jose[cryptography]>=3.3.0",
    "pytest>=8.3.0",
    "flake8>=7.1.0",
    "torch>=2.4.0"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/your-username/vial.github.io"
Repository = "https://github.com/your-username/vial.github.io"
Documentation = "https://your-username.github.io/vial.github.io/docs"
