```yaml
name: Settings Menu Check

on:
  push:
    branches:
      - main

jobs:
  check-settings-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Settings Menu
        run: |
          node -e "const fs = require('fs'); const html = fs.readFileSync('index.html', 'utf8'); const menuCount = (html.match(/id="settings-menu"/g) || []).length; if (menuCount > 1) throw new Error('Multiple settings menus detected');"

      - name: Post Menu Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.issue.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Settings menu check completed at 05:36 PM EDT.'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
