```yaml
name: SVG Layer Limit Check

on:
  push:
    branches:
      - main

jobs:
  check-svg-layer-limit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate SVG Layers
        run: |
          node -e "const fs = require('fs'); const svg = fs.readFileSync('public/assets/dropship/default.svg', 'utf8'); const parser = new DOMParser(); const doc = parser.parseFromString(svg, 'image/svg+xml'); const layers = doc.getElementsByTagName('g'); if (layers.length > 15) throw new Error('Exceeded SVG layer limit of 15');"

      - name: Post Layer Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'SVG layer limit check completed at 06:02 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
