```yaml
name: SVG Layer Check

on:
  push:
    branches:
      - main

jobs:
  check-svg-layers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate SVG Layers
        run: |
          node -e "const fs = require('fs'); const svg = fs.readFileSync('public/assets/dropship/default.svg', 'utf8'); const parser = new DOMParser(); const doc = parser.parseFromString(svg, 'image/svg+xml'); const layers = doc.getElementsByTagName('g'); if (layers.length > 10) console.log('Excessive layers detected.'); else console.log('SVG layer check passed.');"

      - name: Post Layer Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.issue.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'SVG layer check completed at 05:33 PM EDT.'
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
