```yaml
name: SVG Color Check

on:
  push:
    branches:
      - main

jobs:
  check-svg-color:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate SVG Colors
        run: |
          node -e "const fs = require('fs'); const svg = fs.readFileSync('public/assets/dropship/default.svg', 'utf8'); const colors = svg.match(/#[0-9A-Fa-f]{6}/g) || []; const valid = colors.every(c => ['#00ff00', '#000000'].includes(c.toLowerCase())); if (!valid) throw new Error('Invalid SVG colors');"

      - name: Post Color Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'SVG color check completed at 05:52 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
