```yaml
name: Terminal Injection Check

on:
  push:
    branches:
      - main

jobs:
  check-terminal-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Terminal Input
        run: |
          node -e "const input = 'test; rm -rf /'; const sanitized = input.replace(/[;&|]/g, ''); if (sanitized !== 'test') throw new Error('Injection detected');"

      - name: Post Injection Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Terminal injection check completed at 06:02 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
