```yaml
name: Token Check

on:
  issues:
    types: [opened]

jobs:
  verify-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Token and Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const user = await github.rest.users.getAuthenticated();
              const issueNumber = context.issue.number;
              if (issueNumber) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: 'Token verified. Issue opened successfully.'
                });
              }
            } catch (error) {
              console.error('Token error:', error.message);
              throw error;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
