mcp_alchemist:
  version: 1.1.0
  tasks:
    enabled: true
    types:
      - train_model
      - create_agent
      - create_endpoint
      - quantum_circuit
    langchain:
      prompt_template: "Execute task {task_name} with parameters: {params}"
      max_retries: 3
    langgraph:
      nodes:
        - execute_task
        - save_result
      edges:
        - from: execute_task
          to: save_result
        - from: save_result
          to: end
  quantum:
    enabled: true
    default_qubits: 4
    supported_gates:
      - H
      - CNOT
      - X
      - Z
  session:
    ttl: 3600
    track_activities:
      enabled: true
      actions:
        - drag_drop
        - tool_select
        - endpoint_create
