apiVersion: v1
kind: Service
metadata:
  name: validator-service
  labels:
    app: webxos-validator
spec:
  ports:
  - port: 8005
    targetPort: 8005
  selector:
    app: webxos-validator
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-deployment
  labels:
    app: webxos-validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webxos-validator
  template:
    metadata:
      labels:
        app: webxos-validator
    spec:
      containers:
      - name: validator
        image: webxos-validator:latest
        ports:
        - containerPort: 8005
        env:
        - name: DATABASE_URL
          value: "sqlite:///wallet.db"
        - name: RUBE_SERVER_URL
          value: "https://api.rube.app"
        - name: RUBE_TOKEN
          valueFrom:
            secretKeyRef:
              name: rube-secrets
              key: rube-token
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
