version: '3.8'
services:
  maml-gateway:
    image: webxos-maml-gateway:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/maml_database
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    depends_on:
      - mongo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    networks:
      - maml_network

  mongo:
    image: mongo:5.0
    volumes:
      - maml_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=maml_database
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - maml_network

networks:
  maml_network:
    driver: bridge

volumes:
  maml_data:
