apiVersion: v1
kind: Namespace
metadata:
  name: maml-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maml-monitoring-deployment
  namespace: maml-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maml-monitoring
  template:
    metadata:
      labels:
        app: maml-monitoring
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      - name: grafana
        image: grafana/grafana:8.5.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: grafana-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: maml-monitoring-service
  namespace: maml-monitoring
spec:
  selector:
    app: maml-monitoring
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: maml-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'maml-gateway'
        static_configs:
          - targets: ['maml-gateway-service.maml-gateway.svc.cluster.local:8000']
