# File Route: /chimera/chimera_helm_chart.yaml
# Purpose: Helm chart for deploying CHIMERA 2048 API Gateway on Kubernetes.
# Description: Deploys a scalable CHIMERA gateway with DSPy, Qiskit, and BELUGA support,
#              enabling quantum-enhanced workflows and self-regenerating heads.
# Version: 1.0.0
# Publishing Entity: WebXOS Research Group
# Publication Date: August 28, 2025
# Copyright: © 2025 Webxos. All Rights Reserved.

apiVersion: v2
name: chimera-2048
description: Helm chart for CHIMERA 2048 API Gateway
version: 1.0.0
appVersion: "1.0.0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chimera-2048
spec:
  replicas: [YOUR_REPLICAS]  # e.g., 3
  selector:
    matchLabels:
      app: chimera-2048
  template:
    metadata:
      labels:
        app: chimera-2048
    spec:
      containers:
      - name: chimera
        image: chimera-2048:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "[YOUR_DATABASE_URL]"  # e.g., postgresql://user:pass@localhost/chimera
        - name: OBS_STREAM_URL
          value: "[YOUR_OBS_STREAM_URL]"  # e.g., rtmp://localhost/live
        - name: AES_MODE
          value: "[YOUR_AES_MODE]"  # e.g., AES-256 or AES-2048
        volumeMounts:
        - name: maml-volume
          mountPath: /app/maml
      volumes:
      - name: maml-volume
        hostPath:
          path: "[YOUR_MAML_PATH]"  # e.g., /project-dunes/maml
      imagePullSecrets:
      - name: [YOUR_REGISTRY_SECRET]  # e.g., docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chimera-2048
spec:
  selector:
    app: chimera-2048
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

# Customization Instructions:
# 1. Set [YOUR_REPLICAS] to the desired number of pods (e.g., 3).
# 2. Set [YOUR_DATABASE_URL] to your database connection string.
# 3. Set [YOUR_OBS_STREAM_URL] to your OBS streaming endpoint.
# 4. Set [YOUR_AES_MODE] to AES-256 (lightweight) or AES-2048 (max).
# 5. Set [YOUR_MAML_PATH] to your MAML directory (e.g., /project-dunes/maml).
# 6. Set [YOUR_REGISTRY_SECRET] to your Docker registry secret.
# 7. Build the Docker image using /chimera/chimera_build.Dockerfile.
# 8. Deploy: `helm install chimera-2048 chimera/chimera_helm_chart.yaml`.
# 9. Scale to AES-2048 or add GPU support with `nvidia.com/gpu` annotations.
# 10. Add custom OCaml specs to /maml/quantum_spec.ml for verification.
