# AMOEBA 2048AES Dropbox Configuration
# Description: Configuration file for Dropbox API integration with AMOEBA 2048AES SDK, specifying access tokens and folder paths.

dropbox:
  access_token: "your_dropbox_access_token"
  app_key: "your_dropbox_app_key"
  app_secret: "your_dropbox_app_secret"
  folder: "/amoeba2048"
  maml_folder: "/amoeba2048/maml"
  results_folder: "/amoeba2048/results"

security:
  private_key_path: "/path/to/private_key.pem"
  public_key_path: "/path/to/public_key.pem"

monitoring:
  prometheus_endpoint: "localhost:9090"
  metrics:
    - dropbox_upload_latency
    - dropbox_download_latency
    - signature_verification_time