# AMOEBA 2048AES CI/CD Workflow
# Description: GitHub Actions workflow for building, testing, and deploying the AMOEBA 2048AES SDK to Docker Hub and Vercel.

name: AMOEBA 2048AES CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nvidia-driver-535 nvidia-cuda-toolkit
          pip install pytest qiskit==1.0.0 torch==2.0.1 pydantic dropbox==11.36.2 cryptography click
      - name: Run tests
        run: pytest test_amoeba2048.py -v
      - name: Build Docker images
        run: |
          docker build -f Dockerfile.dropbox -t amoeba2048_dropbox:latest .
          docker-compose -f docker-compose.yml build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker images
        run: |
          docker tag amoeba2048_dropbox:latest ${{ secrets.DOCKER_USERNAME }}/amoeba2048_dropbox:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/amoeba2048_dropbox:latest
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}