# File: .github/workflows/ci.yml
# Description: CI/CD pipeline for building and testing the Quantum Fortran Network (QFN) system.

name: QFN CI

on: [push, pull_request]

jobs:
  build-and-test-fortran:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server-id: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
      - name: Setup FPM
        uses: fortran-lang/setup-fpm@v1
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gfortran
      - name: Build Server ${{ matrix.server-id }}
        run: fpm build --path ./app_server_${{ matrix.server-id }}

  build-and-test-python:
    runs-on: ubuntu-latest
    needs: build-and-test-fortran
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python Dependencies
        run: |
          pip install -r sdk/python/requirements.txt
          pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Run Python Tests
        run: pytest sdk/python/tests/ -v