```yaml
name: Agora Test

on:
  push:
    branches:
      - main

jobs:
  test-agora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Agora Sender
        run: |
          python server/api/sender_agent.py

      - name: Run Agora Receiver
        run: |
          python server/api/receiver_agent.py &

      - name: Verify Communication
        run: |
          sleep 5
          response=$(curl -s http://localhost:5000)
          if [[ ! $response =~ "processed" ]]; then
            echo "Agora communication failed"
            exit 1
          fi

      - name: Post Test Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Agora test completed at 06:35 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
```
