name: CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: vial/mcp-server:latest
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install vial-mcp k8s/helm-chart.yaml \
            --set image.tag=latest \
            --kubeconfig=${{ secrets.KUBE_CONFIG }}
      - name: Verify deployment
        run: kubectl rollout status deployment/vial-mcp --timeout=5m
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Deployment failed! Check logs.'
            })
