name: Vial MCP CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: vial_mcp
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install
      - name: Run tests
        env:
          PYTHONPATH: .
          TESTING: true
          DATABASE_URL: postgresql://user:password@localhost:5432/vial_mcp
          MONGO_URI: mongodb://localhost:27017
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: pytest vial/ -v --cov=server --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Trigger training
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          curl -X POST http://localhost:8000/v1/jsonrpc \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer test_token" \
            -d '{"jsonrpc":"2.0","method":"vial_train","params":{"vial_id":"vial1","network_id":"54965687-3871-4f3d-a803-ac9840af87c4"},"id":"1"}'
