```yaml
name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest server/tests
      - name: Run ESLint
        run: npx eslint public/js
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: CI Pipeline Failure
          content-filepath: ./test-failure.md
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: webxos/vial.github.io
```
