name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('package.json', 'requirements.txt') }}
      - name: Install Node.js dependencies
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          npm install
          npm ci --omit=dev
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest server/tests/ -v --cov=server --cov-report=xml
      - name: Security scans
        run: |
          pip install bandit safety
          bandit -r server/ -f json
          safety check -r requirements.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
