```yaml
name: CI Pipeline

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post Comment on Issue or PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            if (!issueNumber) {
              console.log('No issue or PR number available in this context. Skipping comment.');
              return;
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: 'Deployment failed! Check logs.'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
