```yaml
name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Node dependencies
        run: npm ci --omit=dev
      - name: Run ESLint
        run: npx eslint public/js/ typescript/src/ --ext .js,.ts
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run Flake8
        run: flake8 server/ --max-line-length=88 --extend-ignore=E203,W503
      - name: Run Tests
        run: pytest server/tests/ -v --cov=server --cov-report=xml
      - name: Notify on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: 'Deployment failed! Check logs.'
            })
```
