name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint typescript/src/ --ext .ts,.tsx
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run Flake8
        run: flake8 server/
      - name: Run Tests
        run: pytest server/tests/ -v --cov=server --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Notify on failure
        if: failure() && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deployment failed! Check logs.
      - name: Log failure for push events
        if: failure() && github.event_name == 'push'
        run: |
          echo "Deployment failed! Check logs." >> logs/ci_failure.log
