```yaml
name: CI and Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint public/js/ --ext .js,.jsx,.ts,.tsx --fix
        continue-on-error: false

      - name: Notify on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Linting Failed'
          content-filepath: .github/ISSUE_TEMPLATE/lint-failure.md
          assignees: 'your-github-username'
          labels: 'bug, lint'
          token: ${{ secrets.GITHUB_TOKEN }}
