name: CI Pipeline

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Code
        run: npm run lint

      - name: Post CI Status
        if: github.event.pull_request.number || github.event.issue.number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.pull_request?.number || context.payload.issue?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'CI completed at 05:47 PM EDT.'
              });
            } else {
              console.log('No issue/PR context available, skipping comment');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          issues: write
          pull-requests: write
