name: CI Action Logs

on: [push, pull_request]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate logs
        run: python server/logs/action_logger.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
