name: CI CUDA and Helm

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up CUDA
        run: |
          sudo apt update
          sudo apt install -y nvidia-cuda-toolkit
          nvidia-smi
      - name: Run CUDA and Helm tests
        run: ./ci/cd/cuda_helm_test.sh
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test_results
