name: CI Lint and Errors

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install golangci-lint
        run: |
          BINDIR="$(git rev-parse --show-toplevel)/bin"
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $BINDIR v2.2.1
      - name: Lint
        run: bin/golangci-lint run
      - name: Log errors
        if: failure()
        run: |
          python server/scripts/error_logger.py ${{ github.event.pull_request.number }} ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
