name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # --- CUSTOMIZATION POINT: Update pip install command with your requirements file ---
          pip install -r requirements.txt
          pip install dune  # Integrate OCaml Dune 3.20.0 for build checks

      - name: Run tests
        run: |
          # --- CUSTOMIZATION POINT: Add your test commands ---
          pytest --cov=./ --cov-report=xml

      - name: Upload artifacts
        # --- CUSTOMIZATION POINT: Replace v3 with v4 for upload-artifact action ---
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./coverage.xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
