name: CI Quantum Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install qiskit torch
          npm install
      - name: Run quantum tests
        run: |
          python server/tests/quantum_test.py
          npm run test-3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
