name: CI Repo Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run translator scan
        run: |
          python server/agents/translator_authenticator.py scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
