```yaml
name: Deploy to DigitalOcean
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          PROMETHEUS_PORT: ${{ secrets.PROMETHEUS_PORT }}
          SPACEX_API_URL: 'https://api.spacexdata.com/v4'
          GIBS_API_URL: 'https://gibs.earthdata.nasa.gov'
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          envs: GITHUB_TOKEN,NASA_API_KEY,OPENAI_API_KEY,SERPER_API_KEY,PROMETHEUS_PORT,SPACEX_API_URL,GIBS_API_URL
          script: |
            docker system prune -f
            echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/webxos/vial-mcp-server:latest
            docker run --env-file ~/env/vial-mcp.env -d -p 8000:8000 -p 1234:1234 --restart on-failure ghcr.io/webxos/vial-mcp-server:latest
```
