name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  issues: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mcp.txt -r requirements-pytorch.txt
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'
      - name: Update Helm dependencies
        run: helm dependency update ./helm/webxos
      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          helm upgrade --install webxos ./helm/webxos --kubeconfig kubeconfig
      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifacts
          path: ./helm/webxos/
