name: MCP Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
        node-version: [ '18' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt
          npm install
      - name: Run Tests
        run: |
          pytest backend/tests/ -v
          npm test
      - name: Build Docker Image
        run: docker build -f backend/Dockerfile -t webxos-maml-gateway:latest .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maml-gateway-image
          path: webxos-maml-gateway:latest
